### ISSUE TITLE
Authed request in loop

### ISSUE THREAD

**Issue by fenooooo** [ewkt/Vinted-Discord-Notifications#13]
Hello i have follow step by step but the request is not successful

![image](https://github.com/user-attachments/assets/ae9032d7-71f4-487a-a4aa-5715d2b745c8)

**Comment by ewkt** [comment]
hi! sorry i pushed a commit with an error in the code and then fixed it 15min later can u try pulling the newest changes?

**Comment by fenooooo** [comment]
I redownloaded the directory and I still have the same problem. The last one was push?

![image](https://github.com/user-attachments/assets/0f2673e2-babe-4929-8f2c-de3c297615c7)

**Comment by ewkt** [comment]
ah then it must be an other problem.
can you log the url the request is being made to pls?
in search.js you can set the last parameter in authorizedRequest to true

**Comment by fenooooo** [comment]
`const apiUrl = `https://www.vinted.fr/api/v2/catalog/items?search_text=${ids.text}&catalog_ids=${ids.catalog}&price_from=${ids.min}&price_to=${ids.max}&currency=${ids.currency}&catalog_from=0&size_ids=${ids.size}&brand_ids=${ids.brand}&status_ids=${ids.status}&color_ids=${ids.colour}&patterns_ids=${ids.pattern}&material_ids=${ids.material}&order=newest_first&page=1&per_page=10`;`

**Comment by ewkt** [comment]
console.log(apiUrl);

in the code just under that line please so i can help you debug

**Comment by fenooooo** [comment]
`Logged in as Féno Vinted BOT#2796!
fetching cookies
Started refreshing application (/) commands.
Successfully reloaded application (/) commands.
making an authed request to https://www.vinted.fr/how_it_works
.https://www.vinted.fr/api/v2/catalog/items?search_text=&catalog_ids=&price_from=&price_to=&currency=EUR&catalog_from=0&size_ids=&brand_ids=53&status_ids=&color_ids=&patterns_ids=&material_ids=&order=newest_first&page=1&per_page=10
.https://www.vinted.fr/api/v2/catalog/items?search_text=&catalog_ids=&price_from=&price_to=&currency=EUR&catalog_from=0&size_ids=&brand_ids=12&status_ids=&color_ids=&patterns_ids=&material_ids=&order=newest_first&page=1&per_page=10
.https://www.vinted.fr/api/v2/catalog/items?search_text=zara hommes&catalog_ids=&price_from=&price_to=&currency=EUR&catalog_from=0&size_ids=208,209&brand_ids=&status_ids=6,1&color_ids=&patterns_ids=&material_ids=&order=newest_first&page=1&per_page=10
.https://www.vinted.fr/api/v2/catalog/items?search_text=&catalog_ids=&price_from=&price_to=&currency=EUR&catalog_from=0&size_ids=&brand_ids=12&status_ids=&color_ids=&patterns_ids=&material_ids=&order=newest_first&page=1&per_page=10
.https://www.vinted.fr/api/v2/catalog/items?search_text=&catalog_ids=&price_from=&price_to=&currency=EUR&catalog_from=0&size_ids=&brand_ids=53&status_ids=&color_ids=&patterns_ids=&material_ids=&order=newest_first&page=1&per_page=10
.https://www.vinted.fr/api/v2/catalog/items?search_text=zara hommes&catalog_ids=&price_from=&price_to=&currency=EUR&catalog_from=0&size_ids=208,209&brand_ids=&status_ids=6,1&color_ids=&patterns_ids=&material_ids=&order=newest_first&page=1&per_page=10
.https://www.vinted.fr/api/v2/catalog/items?search_text=&catalog_ids=&price_from=&price_to=&currency=EUR&catalog_from=0&size_ids=&brand_ids=12&status_ids=&color_ids=&patterns_ids=&material_ids=&order=newest_first&page=1&per_page=10
.https://www.vinted.fr/api/v2/catalog/items?search_text=&catalog_ids=&price_from=&price_to=&currency=EUR&catalog_from=0&size_ids=&brand_ids=12&status_ids=&color_ids=&patterns_ids=&material_ids=&order=newest_first&page=1&per_page=10
.https://www.vinted.fr/api/v2/catalog/items?search_text=&catalog_ids=&price_from=&price_to=&currency=EUR&catalog_from=0&size_ids=&brand_ids=53&status_ids=&color_ids=&patterns_ids=&material_ids=&order=newest_first&page=1&per_page=10
.https://www.vinted.fr/api/v2/catalog/items?search_text=zara hommes&catalog_ids=&price_from=&price_to=&currency=EUR&catalog_from=0&size_ids=208,209&brand_ids=&status_ids=6,1&color_ids=&patterns_ids=&material_ids=&order=newest_first&page=1&per_page=10
.https://www.vinted.fr/api/v2/catalog/items?search_text=&catalog_ids=&price_from=&price_to=&currency=EUR&catalog_from=0&size_ids=&brand_ids=12&status_ids=&color_ids=&patterns_ids=&material_ids=&order=newest_first&page=1&per_page=10`

**Comment by ewkt** [comment]
ok so url are fine, remove that log and add this under const response =...

console.log(response);

**Comment by fenooooo** [comment]
`Logged in as Féno Vinted BOT#2796!
fetching cookies
Started refreshing application (/) commands.
Successfully reloaded application (/) commands.
making an authed request to https://www.vinted.fr/how_it_works
.{
  items: [
    {
      id: 5653105035,
      title: 'Baskets air force Nike',
      price: [Object],
      is_visible: true,
      discount: null,
      brand_title: 'Nike',
      path: '/items/5653105035-baskets-air-force-nike',
      user: [Object],
      conversion: null,
      url: 'https://www.vinted.fr/items/5653105035-baskets-air-force-nike',
      promoted: false,
      photo: [Object],
      favourite_count: 0,
      is_favourite: false,
      badge: null,
      service_fee: [Object],
      total_item_price: [Object],
      view_count: 0,
      size_title: '25',
      content_source: 'catalog',
      status: 'Very good',
      icon_badges: [],
      item_box: [Object],
      search_tracking_params: [Object]
    },
    {
      id: 5653105187,
      title: 'Blaue Nike Jogginghose',
      price: [Object],
      is_visible: true,
      discount: null,
      brand_title: 'Nike',
      path: '/items/5653105187-blaue-nike-jogginghose',
      user: [Object],
      conversion: null,
      url: 'https://www.vinted.fr/items/5653105187-blaue-nike-jogginghose',
      promoted: false,
      photo: [Object],
      favourite_count: 0,
      is_favourite: false,
      badge: null,
      service_fee: [Object],
      total_item_price: [Object],
      view_count: 0,
      size_title: 'S / 36 / 8',
      content_source: 'catalog',
      status: 'Very good',
      icon_badges: [],
      item_box: [Object],
      search_tracking_params: [Object]
    },
    {
      id: 5653105146,
      title: 'TEE shirt',
      price: [Object],
      is_visible: true,
      discount: null,
      brand_title: 'Nike',
      path: '/items/5653105146-tee-shirt',
      user: [Object],
      conversion: null,
      url: 'https://www.vinted.fr/items/5653105146-tee-shirt',
      promoted: false,
      photo: [Object],
      favourite_count: 0,
      is_favourite: false,
      badge: null,
      service_fee: [Object],
      total_item_price: [Object],
      view_count: 0,
      size_title: 'M / 38 / 10',
      content_source: 'catalog',
      status: 'New without tags',
      icon_badges: [],
      item_box: [Object],
      search_tracking_params: [Object]
    },
    {
      id: 5653104811,
      title: 'scarpe da calcio',
      price: [Object],
      is_visible: true,
      discount: null,
      brand_title: 'Nike',
      path: '/items/5653104811-scarpe-da-calcio',
      user: [Object],
      conversion: null,
      url: 'https://www.vinted.fr/items/5653104811-scarpe-da-calcio',
      promoted: false,
      photo: [Object],
      favourite_count: 0,
      is_favourite: false,
      badge: null,
      service_fee: [Object],
      total_item_price: [Object],
      view_count: 0,
      size_title: '44',
      content_source: 'catalog',
      status: 'Good',
      icon_badges: [],
      item_box: [Object],
      search_tracking_params: [Object]
    },
    {
      id: 5653104757,
      title: 'Nike Dunk Low',
      price: [Object],
      is_visible: true,
      discount: null,
      brand_title: 'Nike',
      path: '/items/5653104757-nike-dunk-low',
      user: [Object],
      conversion: null,
      url: 'https://www.vinted.fr/items/5653104757-nike-dunk-low',
      promoted: false,
      photo: [Object],
      favourite_count: 0,
      is_favourite: false,
      badge: null,
      service_fee: [Object],
      total_item_price: [Object],
      view_count: 0,
      size_title: '42',
      content_source: 'catalog',
      status: 'Very good',
      icon_badges: [],
      item_box: [Object],
      search_tracking_params: [Object]
    },......`

**Comment by ewkt** [comment]
ok so you are getting the data properly,

can you try changing Date.now() - 60000 by adding a 0 => Date.now() - 600000 

in the same file.

**Comment by fenooooo** [comment]
Logged in as Féno Vinted BOT#2796!
fetching cookies
Started refreshing application (/) commands.
Successfully reloaded application (/) commands.
making an authed request to https://www.vinted.fr/how_it_works
.
test1 => +10
 Error posting articles: TypeError: Cannot read properties of undefined (reading 'send')
    at file:///C:/Users/jules/Desktop/VINTED%20BOT/src/bot/post.js:47:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async postArticles (file:///C:/Users/jules/Desktop/VINTED%20BOT/src/bot/post.js:65:5)
    at async runSearch (file:///C:/Users/jules/Desktop/VINTED%20BOT/src/bot/run.js:14:13)
    at async runInterval (file:///C:/Users/jules/Desktop/VINTED%20BOT/src/bot/run.js:24:9)
.
test2 => +10
 Error posting articles: TypeError: Cannot read properties of undefined (reading 'send')
    at file:///C:/Users/jules/Desktop/VINTED%20BOT/src/bot/post.js:47:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async postArticles (file:///C:/Users/jules/Desktop/VINTED%20BOT/src/bot/post.js:65:5)
    at async runSearch (file:///C:/Users/jules/Desktop/VINTED%20BOT/src/bot/run.js:14:13)
    at async runInterval (file:///C:/Users/jules/Desktop/VINTED%20BOT/src/bot/run.js:24:9)
.
Zara => +3.
test2 => +9
 Error posting articles: TypeError: Cannot read properties of undefined (reading 'send')
    at file:///C:/Users/jules/Desktop/VINTED%20BOT/src/bot/post.js:47:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async postArticles (file:///C:/Users/jules/Desktop/VINTED%20BOT/src/bot/post.js:65:5)
    at async runSearch (file:///C:/Users/jules/Desktop/VINTED%20BOT/src/bot/run.js:14:13)
    at async runInterval (file:///C:/Users/jules/Desktop/VINTED%20BOT/src/bot/run.js:24:9)
.

**Comment by ewkt** [comment]
ok so i think the issue with your bot is that it cant find which channel to send to, can you check that the channel ID is correct? it should be just a configuration error.
the rest of the logs say that it's working well now!

**Comment by fenooooo** [comment]
It's ok now after this 0 => Date.now() - 600000

ty a lot <3
